In [304]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [305]:
df = pd.read_csv('laptops_Price.csv')

In [306]:
df.head()

,Name,Price,Review,Description
0,Asus VivoBook...,$295.99,14,"Asus VivoBook X441NA-GA190 Chocolate Black, 14..."
1,Prestigio Smar...,$299.00,8,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ..."
2,Prestigio Smar...,$299.00,12,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ..."
3,Aspire E1-510,$306.99,2,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux"
4,Lenovo V110-15...,$321.94,5,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1..."

In [325]:
df['brand'] = df['Name'].str.extract(
    r'^(Asus|Lenovo|HP|Dell|Acer|Apple|MSI|Samsung|Toshiba|Huawei|Xiaomi|Microsoft|Google|Chuwi|Fujitsu|LG|Mediacom|Prestigio|Aspire)'
)
df['screen_size'] = df['Description'].str.extract(r'(\d{2}\.?\d*)["\s]?(?:inch|")')
df['cpu'] = df['Description'].str.extract(
    r'(Core i[3579][-\w]*|i[3579][-\w]*|Ryzen \d[\s\w-]*|Celeron[\s\w-]*|Pentium[\s\w-]*|AMD A\d[\w-]*|AMD E\d[\w-]*|Xeon[\s\w-]*|Atom[\s\w-]*|M1|M2)'
)
df['os'] = df['Description'].str.extract(
    r'(Windows\s?\d+|Windows|Win\d+\s?Pro\s?\d*bit|Mac OS|Core\s?\d+|macOS|Ubuntu|DOS|Linux|Chrome OS|No OS|Endless OS)'
)
df['ram'] = df['Description'].str.extract(
    r'(\d+\s?GB)'
)
df['storage'] = df['Description'].str.extract(
    r'((?:32|64|128|256|240|750|180|500|512|1000|1|2)\s?(?:GB|TB)(?:\s?(?:SSD|HDD|eMMC|Flash Storage))?)'
)

In [ ]:
# Price is already float64, no need to process it
# df["Price"] = df["Price"].str.replace('$', '').str.replace(',', '').astype(float)

AttributeError: Can only use .str accessor with string values!

In [327]:
df.head()

,Name,Price,Review,Description,brand,screen_size,cpu,os,ram,storage
0,Asus VivoBook...,295.99,14,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",Asus,14,Celeron N3450,Endless OS,4GB,128GB SSD
1,Prestigio Smar...,299.00,8,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",Prestigio,13.3,Celeron N3350 1,Windows 10,4GB,32GB
2,Prestigio Smar...,299.00,12,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",Prestigio,13.3,Celeron N3350 1,Windows 10,4GB,32GB
3,Aspire E1-510,306.99,2,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",Aspire,15.6,Pentium N3520 2,Linux,4GB,500GB
4,Lenovo V110-15...,321.94,5,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",Lenovo,15.6,Celeron N3350 1,Windows 10,4GB,128GB SSD

In [320]:
df.shape

(117, 10)

In [321]:
#filling missing values

df['brand'] = df['brand'].fillna('Unknown')
df['os'] = df['os'].fillna('macOS')

In [328]:
df.isnull().sum()

Name            0
Price           0
Review          0
Description     0
brand          12
screen_size     0
cpu             0
os              6
ram             0
storage         0
dtype: int64

In [323]:
df[df['storage'].isnull()][['Description']]

Empty DataFrame
Columns: [Description]
Index: []