In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [2]:
df = pd.read_csv('laptops_Price.csv')

In [3]:
df.head()

,Name,Price,Review,Description
0,Asus VivoBook...,$295.99,14,"Asus VivoBook X441NA-GA190 Chocolate Black, 14..."
1,Prestigio Smar...,$299.00,8,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ..."
2,Prestigio Smar...,$299.00,12,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ..."
3,Aspire E1-510,$306.99,2,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux"
4,Lenovo V110-15...,$321.94,5,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1..."

In [4]:
df.sample

<bound method NDFrame.sample of                   Name      Price  Review  \
0     Asus VivoBook...    $295.99      14
1    Prestigio Smar...    $299.00       8
2    Prestigio Smar...    $299.00      12
3        Aspire E1-510    $306.99       2
4    Lenovo V110-15...    $321.94       5
..                 ...        ...     ...
112   Lenovo Legion...  $1,399.00       8
113  Asus ROG Strix...  $1,399.00      10
114  Asus ROG Strix...  $1,769.00       7
115  Asus ROG Strix...  $1,769.00       8
116  Asus ROG Strix...  $1,799.00       8

                                           Description
0    Asus VivoBook X441NA-GA190 Chocolate Black, 14...
1    Prestigio SmartBook 133S Dark Grey, 13.3" FHD ...
2    Prestigio SmartBook 133S Gold, 13.3" FHD IPS, ...
3      15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux
4    Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1...
..                                                 ...
112  Lenovo Legion Y720, 15.6" FHD IPS, Core i7-770...
113  Asus ROG Strix GL702VM-GC146T, 17.3" FHD, Core...
114  Asus ROG Strix GL702ZC-GC154T, 17.3" FHD, Ryze...
115  Asus ROG Strix GL702ZC-GC209T, 17.3" FHD IPS, ...
116  Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...

[117 rows x 4 columns]>

In [5]:
df.columns

Index(['Name', 'Price', 'Review', 'Description'], dtype='object')

In [7]:
df["Description"].value_counts()

Description
Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home                                                      2
Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd                                               1
Lenovo Yoga 720 Grey, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, Windows 10 Home                                        1
Lenovo IdeaPad Miix 510 Platinum Silver, 12.2" IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro                                       1
Toshiba Portege X30-D-10J Black/Blue, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro                                                1
                                                                                                                                                 ..
Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux                                                           1
Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home                                                    1
Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux                                                  1
Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home                                                           1
Asus ROG Strix SCAR Edition GL503VM-ED115T, 15.6" FHD 120Hz, Core i7-7700HQ, 16GB, 256GB SSD + 1TB SSHD, GeForce GTX 1060 6GB, Windows 10 Home    1
Name: count, Length: 116, dtype: int64

In [11]:
df['brand_name'] = df.Name.str.lower().str.split().str[0]
df['ram'] = df['Description'].str.lower().str.extract(r'(\d+gb)')
df['screen_size'] = df['Description'].str.lower().str.extract(r'(\d{2}\.\d|\d{1,2}\.\d)\"')
df['cpu'] = df['Description'].str.lower().str.extract(r'(core i\d-\d+u|core i\d-\d+hq|pentium|celeron|ryzen \d|amd [a-z0-9-]+)')
df['os'] = df['Description'].str.lower().str.extract(r'(windows 10|windows 8\.1|linux|dos|endless os|win7)')

In [13]:
df.head()

,Name,Price,Review,Description,brand_name,ram,screen_size,cpu,os
0,Asus VivoBook...,$295.99,14,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",asus,4gb,NaN,celeron,endless os
1,Prestigio Smar...,$299.00,8,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",prestigio,4gb,13.3,celeron,windows 10
2,Prestigio Smar...,$299.00,12,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",prestigio,4gb,13.3,celeron,windows 10
3,Aspire E1-510,$306.99,2,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",aspire,4gb,15.6,pentium,linux
4,Lenovo V110-15...,$321.94,5,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",lenovo,4gb,15.6,celeron,windows 10

In [14]:
df.isnull().sum()

Name            0
Price           0
Review          0
Description     0
brand_name      0
ram             0
screen_size    22
cpu             8
os              9
dtype: int64

In [ ]:
# convert screen_size to numeric then fill NaNs with the mean
df['screen_size'] = pd.to_numeric(df['screen_size'], errors='coerce')
df['screen_size'].fillna(df['screen_size'].mean(), inplace=True)

TypeError: unsupported operand type(s) for +: 'int' and 'str'